project:
  type: website
  pre-render:
    - Rscript copy_files.R
  resources:
    - PDFs
    - scripts/02_excercises/downloads/*.qmd
  render:
    - "*.qmd"
    - "scripts/**/*.qmd"
    - "!scripts/02_excercises/downloads/*.qmd"

website:
  title: "R u Ready"
  site-url: https://r-you-ready.github.io/Webseite_HS26_Seminar/
  sidebar:
    style: floating
    search: true
    collapse-level: 1
    logo: images/ryouready_logo.png
    active-link: true
    contents:
      - href: index.qmd
        text: "Einleitung"
      - href: scripts/01_slides/0_presentation.qmd
        text: "Präsentationen"
        contents:
          - href: scripts/01_slides/EH_1.qmd
            text: "Einheit 1 - 16.09.2026"
          - href: scripts/01_slides/EH_2.qmd
            text: "Einheit 2 - 23.09.2026"
      - href: scripts/02_excercises/Übungen.qmd
        text: "Übungen zu den Einheiten"
        contents: 
          - href: scripts/02_excercises/loesung_1.qmd
            text: "Hands-on 1 (Woche 1 - 2)"
      - href: hausuebungen.qmd
        text: "Hausübungen"
        contents:
          - href: scripts/02_excercises/datenanalyseplan.qmd
            text: "Datenanalyseplan (07.10.26)"
      - href: scripts/04_misc/wettbewerb_cheatsheet.qmd
        text: "Wettbewerb: R-Cheatsheet"
      - href: scripts/04_misc/muddiest_points.qmd
        text: "Muddiest Points"
        contents:
      - href: scripts/03_faq/faq.qmd
        text: "FAQ"
        contents:
          - href: scripts/03_faq/rstudio.qmd
            text: "1  RStudio"
            contents:
              - href: scripts/03_faq/fehlermeldungen.qmd
                text: "1.1  Fehlermeldungen"
          - href: scripts/03_faq/codebook.qmd
            text: "2  Codebook"
          - href: scripts/03_faq/datenanalyseplan.qmd
            text: "3  Datenanalyseplan"
          - href: scripts/03_faq/statistic.qmd
            text: "4  Statistik"
          - href: scripts/03_faq/endabgabe.qmd
            text: "5  Abschlussprojekt"
      - href: scripts/04_misc/here.qmd
        text: "Probleme beim Rendern"
      - href: scripts/04_misc/links_und_ressourcen.qmd
        text: "Links und Ressourcen"
        contents:
          - href: scripts/04_misc/LLMs.qmd
            text: "LLMs in RStudio"
          - href: scripts/04_misc/Memes.qmd
            text: "Memes :)"
      - href: scripts/04_misc/leistungsnachweis.qmd
        text: "Leistungsnachweis"
      - href: scripts/04_misc/about.qmd
        text: "About"

format:
  html:
    toc: true
    toc-expand: false
    css:
      - styles.css
      - styles/website_styles.css

